### ISSUE TITLE
SystemError: Invalid argument

### ISSUE THREAD

**Issue by yeliudev** [wxy1343/aliyunpan#13]
python main.py upload -p /xxx

```
Traceback (most recent call last):
  File "/project/liuye/aliyunpan/main.py", line 114, in <module>
    cli()
  File "/home/liuye/project/miniconda3/envs/drive/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/liuye/project/miniconda3/envs/drive/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/liuye/project/miniconda3/envs/drive/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/liuye/project/miniconda3/envs/drive/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/liuye/project/miniconda3/envs/drive/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/project/liuye/aliyunpan/main.py", line 69, in upload
    commander.upload(path_list, upload_path, time_out, retry, force)
  File "/project/liuye/aliyunpan/aliyunpan/cli/cli.py", line 97, in upload
    self._disk.upload_file(self._path_list.get_path_fid(file[0]), *file[1])
  File "/project/liuye/aliyunpan/aliyunpan/api/utils.py", line 49, in decorated
    return loop.run_until_complete(f(*args, **kwargs))
  File "/home/liuye/project/miniconda3/envs/drive/lib/python3.9/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/home/liuye/project/miniconda3/envs/drive/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/home/liuye/project/miniconda3/envs/drive/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/project/liuye/aliyunpan/aliyunpan/api/core.py", line 165, in upload_file
    chunk = await f.read(split_size)
  File "/home/liuye/project/miniconda3/envs/drive/lib/python3.9/site-packages/aiofile/utils.py", line 211, in read
    return await self.__read(length)
  File "/home/liuye/project/miniconda3/envs/drive/lib/python3.9/site-packages/aiofile/utils.py", line 205, in __read
    data = await self.file.read_bytes(length, self._offset)
  File "/home/liuye/project/miniconda3/envs/drive/lib/python3.9/site-packages/aiofile/aio.py", line 202, in read_bytes
    return await self.__context.read(size, self.fileno(), offset)
  File "/home/liuye/project/miniconda3/envs/drive/lib/python3.9/site-packages/caio/asyncio_base.py", line 88, in submit
    return op.get_value()
SystemError: Invalid argument
```

**Comment by yeliudev** [comment]
现在发现的只有zip和png文件会报错，其他文件正常

**Comment by wxy1343** [comment]
我这边很正常，无法重现bug，请提供具体的系统环境和运行的命令，方便的话可以提供不能上传的文件

**Comment by yeliudev** [comment]
系统版本：Linux version 3.10.0-862.14.4.el7.x86_64
运行的命令：python main.py upload -p /xxx（其中xxx是包含四个zip文件的文件夹，每个文件约20G，所以不好提供）

**Comment by yeliudev** [comment]
使用这个仓库可以上传，但是不会失败重试：https://github.com/Hidove/aliyundrive-uploader
有没可能是异步的原因呢？

**Comment by wxy1343** [comment]
确实和异步有关，测试了一下在linux环境下，异步读取超过2GB的文件会发生此错误
```python3
import asyncio
import aiofile


async def read_file(path):
    count = 0
    async with aiofile.async_open(path, 'rb') as f:
        while True:
            try:
                chunk = await f.read(1024 * 1024)
            except SystemError:
                print(count)
                exit()
            count += 1


asyncio.run(read_file('1'))

```
```r
$ dd if=/dev/zero of=1 bs=1G count=5
5+0 records in
5+0 records out
5368709120 bytes (5.4 GB, 5.0 GiB) copied, 16.5373 s, 325 MB/s
$ python3 1.py
2048
```

**Comment by wxy1343** [comment]
https://github.com/mosquito/aiofile/issues/53#issuecomment-761886747 可以增加此代码解决
```python3
import caio
second = caio.variants[1]
second_asyncio = caio.variants_asyncio[1]
caio.Context = second.Context      # type: ignore
caio.Operation = second.Operation  # type: ignore
caio.AsyncioContext = second_asyncio.AsyncioContext   # type: ignore
```

**Comment by yeliudev** [comment]
谢谢！
