### ISSUE TITLE
账号和密码登陆失败

### ISSUE THREAD

**Issue by Kimentanm** [wxy1343/aliyunpan#19]
错误日志
```shell
Traceback (most recent call last):
  File "main.py", line 125, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 24, in cli
    commander.init(config_file=config_file, depth=depth)
  File "/root/backup/aliyunpan/aliyunpan/cli/cli.py", line 57, in init
    raise LoginFailed
aliyunpan.exceptions.LoginFailed
```

**Comment by wxy1343** [comment]
网页可以登录吗
是否需要登录验证

**Comment by Kimentanm** [comment]
网页可以登录，不需要登录验证，一样的用户名和密码，就很奇怪

**Comment by wxy1343** [comment]
> 网页可以登录，不需要登录验证，一样的用户名和密码，就很奇怪

登录的ip一样吗

**Comment by Kimentanm** [comment]
> > 网页可以登录，不需要登录验证，一样的用户名和密码，就很奇怪
> 
> 登录的ip一样吗

登录IP不一样

**Comment by wxy1343** [comment]
> > > 网页可以登录，不需要登录验证，一样的用户名和密码，就很奇怪
> > 
> > 
> > 登录的ip一样吗
> 
> 登录IP不一样

可能有的ip需要验证
