### ISSUE TITLE
ModuleNotFoundError: No module named 'ruamel.yaml'

### ISSUE THREAD

**Issue by tongjun741** [wxy1343/aliyunpan#20]
```
(base) ➜  aliyunpan git:(main) ✗ python main.py -h
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from aliyunpan.cli.cli import Commander
  File "/Users/tongjun/workspace/aliyunpan/aliyunpan/cli/__init__.py", line 1, in <module>
    from aliyunpan.cli.cli import Commander
  File "/Users/tongjun/workspace/aliyunpan/aliyunpan/cli/cli.py", line 7, in <module>
    from aliyunpan.cli.config import Config
  File "/Users/tongjun/workspace/aliyunpan/aliyunpan/cli/config.py", line 2, in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel.yaml'
(base) ➜  aliyunpan git:(main) ✗ pip install ruamel_yaml
Requirement already satisfied: ruamel_yaml in /Users/tongjun/anaconda3/lib/python3.7/site-packages (0.15.46)
WARNING: You are using pip version 21.0.1; however, version 21.1.2 is available.
You should consider upgrading via the '/Users/tongjun/anaconda3/bin/python -m pip install --upgrade pip' command.
(base) ➜  aliyunpan git:(main) ✗ python --version
Python 3.7.4
```

**Comment by tongjun741** [comment]
是我的问题，mac上有两个python3，指定python的具体版本后就好了：
```
python3 -m pip install -r ./requirements.txt
python3 main.py -h
```
