### ISSUE TITLE
TypeError: unlink() got an unexpected keyword argument 'missing_ok'

### ISSUE THREAD

**Issue by Lujango** [wxy1343/aliyunpan#21]
Exception ignored in: <bound method Commander.__del__ of <aliyunpan.cli.cli.Commander object at 0x107074c18>>
Traceback (most recent call last):
  File "/Users/lujango/Downloads/aliyunpan-main/aliyunpan/cli/cli.py", line 29, in __del__
  File "/Users/lujango/Downloads/aliyunpan-main/aliyunpan/cli/config.py", line 25, in write
TypeError: unlink() got an unexpected keyword argument 'missing_ok'

**Comment by Lujango** [comment]
aliyunpan-main python3.6 main.py mkdir hehe

[+][mkdir]hehe
Exception ignored in: <bound method Commander.__del__ of <aliyunpan.cli.cli.Commander object at 0x1047cfc50>>
Traceback (most recent call last):
  File "/Users/lujango/Downloads/aliyunpan-main/aliyunpan/cli/cli.py", line 29, in __del__
  File "/Users/lujango/Downloads/aliyunpan-main/aliyunpan/cli/config.py", line 25, in write
TypeError: unlink() got an unexpected keyword argument 'missing_ok'

**Comment by Lujango** [comment]
执行命令都会报一个错，命令最后是成功的

**Comment by wxy1343** [comment]
https://github.com/python/cpython/pull/6191/commits/4277aab33b229150228671918d2a1cf91e13b6ea

**Comment by wxy1343** [comment]
你python版本太低了
