### ISSUE TITLE
refreshtoken失效

### ISSUE THREAD

**Issue by ifuweimin** [wxy1343/aliyunpan#28]
已经用过一段时间了没问题，从昨天开始token失效，可能是阿里云盘调整了策略？

Traceback (most recent call last):
  File "/opt/code/aliyunpan/aliyunpan/api/core.py", line 422, in get_access_token
    access_token = r.json()['access_token']
KeyError: 'access_token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/aliyunpan/main.py", line 152, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/code/aliyunpan/main.py", line 87, in upload
    commander.upload(path_list, upload_path, time_out, retry, force, share, chunk_size, c)
  File "/opt/code/aliyunpan/aliyunpan/cli/cli.py", line 181, in upload
    return self.upload_share(share_list, upload_path, force)
  File "/opt/code/aliyunpan/aliyunpan/cli/cli.py", line 263, in upload_share
    file_id_list = self.mkdir(upload_path / path)
  File "/opt/code/aliyunpan/aliyunpan/cli/cli.py", line 128, in mkdir
    file_id = self._path_list.get_path_fid(path, update=False)
  File "/opt/code/aliyunpan/aliyunpan/api/models.py", line 96, in get_path_fid
    self.auto_update_path_list(update, file_id)
  File "/opt/code/aliyunpan/aliyunpan/api/models.py", line 125, in auto_update_path_list
    return self.update_path_list(file_id, depth=0)
  File "/opt/code/aliyunpan/aliyunpan/api/models.py", line 23, in update_path_list
    file_list = self._disk.get_file_list(file_id)
  File "/opt/code/aliyunpan/aliyunpan/api/core.py", line 81, in get_file_list
    json = {"drive_id": self.drive_id, "parent_file_id": parent_file_id, 'fields': '*', 'marker': next_marker}
  File "/opt/code/aliyunpan/aliyunpan/api/core.py", line 34, in <lambda>
    drive_id = property(lambda self: next(self._drive_id_gen_),
  File "/opt/code/aliyunpan/aliyunpan/api/core.py", line 466, in _drive_id_gen
    drive_id = self.get_drive_id()
  File "/opt/code/aliyunpan/aliyunpan/api/core.py", line 449, in get_drive_id
    drive_id = self.get_user_info().drive_id
  File "/opt/code/aliyunpan/aliyunpan/api/core.py", line 157, in get_user_info
    r = self._req.post(url, json={})
  File "/opt/code/aliyunpan/aliyunpan/api/req.py", line 47, in post
    return self._req('post', *args, **kwargs)
  File "/opt/code/aliyunpan/aliyunpan/api/req.py", line 37, in _req
    kwargs['headers']['Authorization'] = self.disk.access_token if self.disk else GLOBAL_VAR.access_token
  File "/opt/code/aliyunpan/aliyunpan/api/core.py", line 32, in <lambda>
    access_token = property(lambda self: next(self._access_token_gen_),
  File "/opt/code/aliyunpan/aliyunpan/api/core.py", line 442, in _access_token_gen
    access_token = self.get_access_token()
  File "/opt/code/aliyunpan/aliyunpan/api/core.py", line 424, in get_access_token
    raise InvalidRefreshToken
aliyunpan.exceptions.InvalidRefreshToken: Is not a valid refresh_token.

**Comment by wxy1343** [comment]
refresh_token好像也会过期，重新获取一个就行了

**Comment by ifuweimin** [comment]
好的，我再观察看看，因为昨天中午已经通过app换过一次最新的了，今早上发现又不行了，我以为这个也会失效的时候自动请求最新的
