### ISSUE TITLE
上传过程中出现异常

### ISSUE THREAD

**Issue by 821938089** [wxy1343/aliyunpan#30]
这两个异常都出现了好几次了

第一个：
```
Traceback (most recent call last):
  File "D:\Python\b站直播姬webhook\FileUpload.py", line 144, in upload
    if not commander.upload(path=file, upload_path=upload_path,
  File "D:\Python\b站直播姬webhook\aliyunpan\cli\cli.py", line 211, in upload
    result = self._disk.upload_file(
  File "D:\Python\b站直播姬webhook\aliyunpan\api\core.py", line 416, in upload_file
    upload_bar.update(ratio=k, refresh_line=True)
  File "D:\Python\b站直播姬webhook\aliyunpan\common.py", line 314, in update
    self.output = Info(upload_info, refresh_line=refresh_line, color=Fore.LIGHTMAGENTA_EX)
  File "D:\Python\b站直播姬webhook\aliyunpan\common.py", line 193, in <lambda>
    lambda self, value: self._print.output.send(value) if self._output else None)
ValueError: generator already executing
```
FileUpload.py的upload函数是通过线程来启动的，我查过似乎是多线程的问题

第二个：
```
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 436, in _error_catcher
    yield
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 766, in read_chunked
    chunk = self._handle_chunk(amt)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 710, in _handle_chunk
    value = self._fp._safe_read(amt)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 612, in _safe_read
    data = self.fp.read(amt)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 571, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 792, in read_chunked
    self._original_response.close()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 441, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\b站直播姬webhook\FileUpload.py", line 144, in upload
    if not commander.upload(path=file, upload_path=upload_path,
  File "D:\Python\b站直播姬webhook\aliyunpan\cli\cli.py", line 211, in upload
    result = self._disk.upload_file(
  File "D:\Python\b站直播姬webhook\aliyunpan\api\core.py", line 309, in upload_file
    r = self.create_file(file_name=file_name, parent_file_id=parent_file_id, file_type=True, json=json,
  File "D:\Python\b站直播姬webhook\aliyunpan\api\core.py", line 214, in create_file
    r = self._req.post(url, json=j)
  File "D:\Python\b站直播姬webhook\aliyunpan\api\req.py", line 76, in post
    return self._req('post', *args, **kwargs)
  File "D:\Python\b站直播姬webhook\aliyunpan\api\req.py", line 47, in _req
    r = getattr(self._session, method.lower())(*args, **kwargs)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 697, in send
    r.content
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 760, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out.
```
这个希望能够给函数create_file的request加重试

**Comment by wxy1343** [comment]
第一个加个锁就好了
第二个是什么情况下出现的

**Comment by 821938089** [comment]
> 第一个加个锁就好了
> 第二个是什么情况下出现的

在计算完文件sha1之后create_file就出错，好几次都这样
我觉得可能是网的问题，在上传的任务占满了上传速度所以有影响
或者可能是session的问题
log:
```
2021-06-17 11:42:14 [FileUpload.py:143] upload DEBUG - 开始上传文件 录制-78121-20210617-100123-581-鲁白给-永劫无间走起,永不下饭.flv
2021-06-17 11:42:14 [utils.py:28] get_sha1 INFO - Calculate sha1 of file E:\B站直播录制\78121-鲁路修兰佩鲁济\录制-78121-20210617-100123-581-鲁白给-永劫无间走起,永不下饭.flv.
2021-06-17 11:42:14 [main.py:124] addLiveStartTime DEBUG - 有新的直播间开播了 roomId: 78121
2021-06-17 11:42:14 [main.py:132] addLiveStartTime DEBUG - 活动的直播间 liveStartTimeList: {'鲁路修兰佩鲁济': '2021.06.17'}
2021-06-17 11:42:20 [utils.py:49] get_sha1 INFO - The SHA1 of file E:\B站直播录制\78121-鲁路修兰佩鲁济\录制-78121-20210617-100123-581-鲁白给-永劫无间走起,永不下饭.flv is 75b345f03bcd490646ea644c0a8a2548f2eafed0.
2021-06-17 11:42:20 [core.py:213] create_file INFO - Create file 录制-78121-20210617-100123-581-鲁白给-永劫无间走起,永不下饭.flv in file 60cac496598ecaf132244d6c8183155742730019.
2021-06-17 11:42:31 [FileUpload.py:183] upload DEBUG - 录制-78121-20210617-100123-581-鲁白给-永劫无间走起,永不下饭.flv 文件上传失败或出现其他异常
        Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 436, in _error_catcher
    yield
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 766, in read_chunked
    chunk = self._handle_chunk(amt)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 710, in _handle_chunk
    value = self._fp._safe_read(amt)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 612, in _safe_read
    data = self.fp.read(amt)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 571, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 792, in read_chunked
    self._original_response.close()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 441, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\b站直播姬webhook\FileUpload.py", line 144, in upload
    if not commander.upload(path=file, upload_path=upload_path,
  File "D:\Python\b站直播姬webhook\aliyunpan\cli\cli.py", line 211, in upload
    result = self._disk.upload_file(
  File "D:\Python\b站直播姬webhook\aliyunpan\api\core.py", line 309, in upload_file
    r = self.create_file(file_name=file_name, parent_file_id=parent_file_id, file_type=True, json=json,
  File "D:\Python\b站直播姬webhook\aliyunpan\api\core.py", line 214, in create_file
    r = self._req.post(url, json=j)
  File "D:\Python\b站直播姬webhook\aliyunpan\api\req.py", line 76, in post
    return self._req('post', *args, **kwargs)
  File "D:\Python\b站直播姬webhook\aliyunpan\api\req.py", line 47, in _req
    r = getattr(self._session, method.lower())(*args, **kwargs)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 697, in send
    r.content
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 760, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out.
```
