### ISSUE TITLE
上传不了了吗？

### ISSUE THREAD

**Issue by ddfiberglass** [wxy1343/aliyunpan#36]
最近上传文件，一直出错，大家有一样的情况吗？前几天还好的。

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/SSL.py", line 1828, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/SSL.py", line 1558, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 491, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: SysCallError(104, 'ECONNRESET')",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='auth.aliyundrive.com', port=443): Max retries exceeded with url: /v2/account/token (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/aliyunpan/main.py", line 183, in <module>
    cli()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/aliyunpan/main.py", line 91, in upload
    commander.upload(path_list, upload_path, time_out, retry, force, share, chunk_size, c)
  File "/root/aliyunpan/aliyunpan/cli/cli.py", line 241, in upload
    result = self._disk.upload_file(
  File "/root/aliyunpan/aliyunpan/api/core.py", line 326, in upload_file
    r = self.create_file(file_name=file_name, parent_file_id=parent_file_id, file_type=True, json=json,
  File "/root/aliyunpan/aliyunpan/api/core.py", line 203, in create_file
    "drive_id": self.drive_id,
  File "/root/aliyunpan/aliyunpan/api/core.py", line 42, in <lambda>
    drive_id = property(lambda self: (self._lock.acquire(), next(self._drive_id_gen_), self._lock.release())[1],
  File "/root/aliyunpan/aliyunpan/api/core.py", line 559, in _drive_id_gen
    drive_id = self.get_drive_id()
  File "/root/aliyunpan/aliyunpan/api/core.py", line 542, in get_drive_id
    drive_id = self.get_user_info().drive_id
  File "/root/aliyunpan/aliyunpan/api/core.py", line 177, in get_user_info
    r = self._req.post(url, json={})
  File "/root/aliyunpan/aliyunpan/api/req.py", line 76, in post
    return self._req('post', *args, **kwargs)
  File "/root/aliyunpan/aliyunpan/api/req.py", line 46, in _req
    kwargs['headers']['Authorization'] = self._disk.access_token if self._disk else GLOBAL_VAR.access_token
  File "/root/aliyunpan/aliyunpan/api/core.py", line 40, in <lambda>
    access_token = property(lambda self: (self._lock.acquire(), next(self._access_token_gen_), self._lock.release())[1],
  File "/root/aliyunpan/aliyunpan/api/core.py", line 535, in _access_token_gen
    access_token = self.get_access_token()
  File "/root/aliyunpan/aliyunpan/api/core.py", line 513, in get_access_token
    r = self._req.post(url, json=json, access_token=False)
  File "/root/aliyunpan/aliyunpan/api/req.py", line 76, in post
    return self._req('post', *args, **kwargs)
  File "/root/aliyunpan/aliyunpan/api/req.py", line 47, in _req
    r = getattr(self._session, method.lower())(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='auth.aliyundrive.com', port=443): Max retries exceeded with url: /v2/account/token (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')")))

**Comment by wxy1343** [comment]
超时设置大一点试试
> https://github.com/wxy1343/aliyunpan/blob/29d74d917c990872f1b82022ac1bd837d0e5d259/aliyunpan/api/req.py#L21

**Comment by ddfiberglass** [comment]
谢谢，改成15秒，可以啦。
