### ISSUE TITLE
在Releases下载的可执行文件运行错误

### ISSUE THREAD

**Issue by dodying** [wxy1343/aliyunpan#37]
我下载并解压了`aliyunpan-cli-Windows-x86_64-v2.6.0-96229c9.tar.gz`后，将aliyunpan.yaml放在`%UserProfiles%\.config\aliyunpan.yaml`，运行`aliyunpan-cli ls`，会报错

错误日志：
```
Traceback (most recent call last):
  File "main.py", line 179, in <module>
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "main.py", line 87, in upload
  File "aliyunpan\cli\cli.py", line 250, in upload
  File "aliyunpan\api\core.py", line 339, in upload_file
  File "aliyunpan\api\core.py", line 216, in create_file
  File "aliyunpan\api\core.py", line 44, in <lambda>
  File "aliyunpan\api\core.py", line 575, in _drive_id_gen
  File "aliyunpan\api\core.py", line 558, in get_drive_id
  File "aliyunpan\api\core.py", line 180, in get_user_info
  File "aliyunpan\api\req.py", line 92, in post
  File "aliyunpan\api\req.py", line 62, in _req
  File "aliyunpan\api\core.py", line 42, in <lambda>
  File "aliyunpan\api\core.py", line 548, in _access_token_gen
  File "aliyunpan\api\core.py", line 526, in get_access_token
  File "aliyunpan\api\req.py", line 92, in post
  File "aliyunpan\api\req.py", line 63, in _req
  File "requests\sessions.py", line 590, in post
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 696, in urlopen
  File "urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "urllib3\connection.py", line 359, in connect
  File "urllib3\connection.py", line 500, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 997, in _create
ValueError: check_hostname requires server_hostname
[9788] Failed to execute script 'main' due to unhandled exception!
```

奇怪的是，我在另一台电脑上正常运行

**Comment by wxy1343** [comment]
把代理关了试试

**Comment by dodying** [comment]
多谢了，才发现启用了系统代理
