### ISSUE TITLE
上传的时候出现错误

### ISSUE THREAD

**Issue by dodying** [wxy1343/aliyunpan#38]
日志：
```
Traceback (most recent call last):
  File "main.py", line 179, in <module>
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "main.py", line 87, in upload
  File "aliyunpan\cli\cli.py", line 250, in upload
  File "aliyunpan\api\core.py", line 373, in upload_file
  File "aliyunpan\common.py", line 236, in upload_info
  File "aliyunpan\common.py", line 202, in <lambda>
  File "aliyunpan\common.py", line 149, in <lambda>
  File "aliyunpan\common.py", line 166, in _output_gen
UnicodeEncodeError: 'gbk' codec can't encode character '\u266a' in position 93: illegal multibyte sequence
[10708] Failed to execute script 'main' due to unhandled exception!
```

文件名是`[web Girlfriend (♪)][01][怡萱动漫][www.yxdm.tv].mp4`

**Comment by wxy1343** [comment]
把♪删了试试

**Comment by dodying** [comment]
现在上传的时候带上参数`UPLOAD_PATH`，比如`aliyunpan-cli upload list.txt test`，会报错
```
Failed to execute script 'main' due to unhandled exception!
```

**Comment by dodying** [comment]
@wxy1343
