### ISSUE TITLE
master分支不可用，dev分支可以报错如下

### ISSUE THREAD

**Issue by ee-e** [wxy1343/aliyunpan#40]
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from aliyunpan.cli.cli import Commander
  File "/aliyunpan/aliyunpan/cli/__init__.py", line 1, in <module>
    from aliyunpan.cli.cli import Commander
  File "/aliyunpan/aliyunpan/cli/cli.py", line 20, in <module>
    class Commander:
  File "/aliyunpan/aliyunpan/cli/cli.py", line 111, in Commander
    def get_path_list(self, path='root') -> list[FileInfo]:
TypeError: 'type' object is not subscriptable

**Comment by wxy1343** [comment]
https://stackoverflow.com/questions/62871524/is-pep-585-unusable-at-runtime-under-python-3-7-and-3-8
