### ISSUE TITLE
上传错误

### ISSUE THREAD

**Issue by drx1x2** [wxy1343/aliyunpan#45]
alpine:/home/aliyun# pip install -r requirements.txt
Ignoring windows-curses: markers 'platform_system == "Windows"' don't match your environment
Requirement already satisfied: treelib==1.6.1 in /usr/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (1.6.1)
Requirement already satisfied: requests~=2.25.1 in /usr/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (2.25.1)
Requirement already satisfied: click_aliases==1.0.1 in /usr/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (1.0.1)
Requirement already satisfied: rsa==4.0 in /usr/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (4.0)
Requirement already satisfied: click==7.1.1 in /usr/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (7.1.1)
Requirement already satisfied: ruamel.base==1.0.0 in /usr/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (1.0.0)
Requirement already satisfied: ruamel.yaml in /usr/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (0.17.7)
Requirement already satisfied: colorama~=0.4.3 in /usr/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (0.4.4)
Requirement already satisfied: npyscreen==4.10.5 in /usr/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (4.10.5)
Requirement already satisfied: pyperclip~=1.8.1 in /usr/lib/python3.9/site-packages (from -r requirements.txt (line 11)) (1.8.2)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/lib/python3.9/site-packages (from rsa==4.0->-r requirements.txt (line 4)) (0.4.8)
Requirement already satisfied: future in /usr/lib/python3.9/site-packages (from treelib==1.6.1->-r requirements.txt (line 1)) (0.18.2)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/lib/python3.9/site-packages (from requests~=2.25.1->-r requirements.txt (line 2)) (4.0.0)
Requirement already satisfied: idna<3.3,>=2.5 in /usr/lib/python3.9/site-packages (from requests~=2.25.1->-r requirements.txt (line 2)) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.9/site-packages (from requests~=2.25.1->-r requirements.txt (line 2)) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.9/site-packages (from requests~=2.25.1->-r requirements.txt (line 2)) (2020.12.5)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2 in /usr/lib/python3.9/site-packages (from ruamel.yaml->-r requirements.txt (line 7)) (0.2.2)
alpine:/home/aliyun# python3 main.py u /unraid/xxx /backup/xxx
Traceback (most recent call last):
  File "/home/aliyun/main.py", line 168, in <module>
    cli()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/aliyun/main.py", line 91, in upload
    commander.upload(path_list, upload_path, time_out, retry, force, share, chunk_size, c)
  File "/home/aliyun/aliyunpan/cli/cli.py", line 248, in upload
    raise FileNotFoundError
FileNotFoundError

alpine:/home/aliyun#

**Comment by drx1x2** [comment]
正常了，原来虚拟机/unraid 目录没挂载
