### ISSUE TITLE
建议更改存放 log 的文件夹

### ISSUE THREAD

**Issue by sukanka** [wxy1343/aliyunpan#79]
目前的 log 所在文件夹为 
https://github.com/wxy1343/aliyunpan/blob/1dd7309196f77a9420b17c2d87df37e8b0193138/aliyunpan/api/utils.py#L18-L21

但是如果把可执行文件放在 `/usr/bin` 会导致 `permission denied`
建议默认 log 放在 `tmpfs` 比如 `/tmp/aliyunpan-cli-PID` 或者放在 `~/.cache/aliyunpan-cli`

最后附一个对应的报错
```
Traceback (most recent call last):
File "/usr/bin/aliyunpan-cli", line 33, in <module>
sys.exit(load_entry_point('aliyunpan==3.0.6', 'console_scripts', 'aliyunpan-cli')())
File "/usr/bin/aliyunpan-cli", line 25, in importlib_load_entry_point
return next(matches).load()
File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
module = import_module(match.group('module'))
File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/usr/lib/python3.10/site-packages/aliyunpan/main.py", line 5, in <module>
from aliyunpan.api.utils import logger
File "/usr/lib/python3.10/site-packages/aliyunpan/api/__init__.py", line 1, in <module>
from aliyunpan.api.core import AliyunPan
File "/usr/lib/python3.10/site-packages/aliyunpan/api/core.py", line 13, in <module>
from aliyunpan.api.req import *
File "/usr/lib/python3.10/site-packages/aliyunpan/api/req.py", line 9, in <module>
from aliyunpan.api.utils import logger
File "/usr/lib/python3.10/site-packages/aliyunpan/api/utils.py", line 25, in <module>
stream=open(log_file, 'a', encoding='utf-8'),
PermissionError: [Errno 13] Permission denied: '/usr/bin/aliyunpan.log'
```

**Comment by wxy1343** [comment]
可以这样运行命令
```ALIYUNPAN_ROOT=/tmp aliyunpan-cli```

**Comment by sukanka** [comment]
> 可以这样运行命令 `ALIYUNPAN_ROOT=/tmp aliyunpan-cli`

对的，您一说我就注意到了可以设置环境变量。谢谢！
