### ISSUE TITLE
使用出错

### ISSUE THREAD

**Issue by LondyGhost** [wxy1343/aliyunpan#84]
系统 ubuntu arm 21.10

>   File "/usr/local/bin/aliyunpan-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/aliyunpan/main.py", line 224, in main
    cli()
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1656, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/aliyunpan/main.py", line 34, in cli
    commander.init(config_file=None if refresh_token or username else config_file,
  File "/usr/local/lib/python3.9/dist-packages/aliyunpan/cli/cli.py", line 72, in init
    if self._config.config_file and self._config.get('aria2'):
  File "/usr/local/lib/python3.9/dist-packages/aliyunpan/cli/config.py", line 52, in get
    conf = self.read()
  File "/usr/local/lib/python3.9/dist-packages/aliyunpan/cli/config.py", line 27, in read
    return yaml.load(f) or {}
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/main.py", line 434, in load
    return constructor.get_single_data()
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/constructor.py", line 119, in get_single_data
    node = self.composer.get_single_node()
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/composer.py", line 76, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/composer.py", line 99, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/composer.py", line 143, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/composer.py", line 223, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/composer.py", line 113, in compose_node
    if self.parser.check_event(AliasEvent):
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/parser.py", line 146, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/parser.py", line 627, in parse_block_mapping_value
    if self.scanner.check_token(ValueToken):
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/scanner.py", line 1796, in check_token
    self._gather_comments()
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/scanner.py", line 1838, in _gather_comments
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/scanner.py", line 312, in fetch_more_tokens
    return self.fetch_single()
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/scanner.py", line 730, in fetch_single
    self.fetch_flow_scalar(style="'")
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/scanner.py", line 743, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/scanner.py", line 1399, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_spaces(double, start_mark))
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/scanner.py", line 1498, in scan_flow_scalar_spaces
    raise ScannerError(
ruamel.yaml.scanner.ScannerError: while scanning a quoted scalar
  in "/home/ubuntu/.config/aliyunpan.yaml", line 1, column 16
found unexpected end of stream
  in "/home/ubuntu/.config/aliyunpan.yaml", line 2, column 1
ubuntu@londy:~$ sudo aliyunpan-cli -t 92b1956dd81d47599b953d570f50f146 u 1.mkv
Traceback (most recent call last):
  File "/usr/local/bin/aliyunpan-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/aliyunpan/main.py", line 224, in main
    cli()
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1656, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/aliyunpan/main.py", line 34, in cli
    commander.init(config_file=None if refresh_token or username else config_file,
  File "/usr/local/lib/python3.9/dist-packages/aliyunpan/cli/cli.py", line 72, in init
    if self._config.config_file and self._config.get('aria2'):
  File "/usr/local/lib/python3.9/dist-packages/aliyunpan/cli/config.py", line 52, in get
    conf = self.read()
  File "/usr/local/lib/python3.9/dist-packages/aliyunpan/cli/config.py", line 27, in read
    return yaml.load(f) or {}
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/main.py", line 434, in load
    return constructor.get_single_data()
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/constructor.py", line 119, in get_single_data
    node = self.composer.get_single_node()
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/composer.py", line 76, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/composer.py", line 99, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/composer.py", line 143, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/composer.py", line 223, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/composer.py", line 113, in compose_node
    if self.parser.check_event(AliasEvent):
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/parser.py", line 146, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/parser.py", line 627, in parse_block_mapping_value
    if self.scanner.check_token(ValueToken):
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/scanner.py", line 1796, in check_token
    self._gather_comments()
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/scanner.py", line 1838, in _gather_comments
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/scanner.py", line 312, in fetch_more_tokens
    return self.fetch_single()
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/scanner.py", line 730, in fetch_single
    self.fetch_flow_scalar(style="'")
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/scanner.py", line 743, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/scanner.py", line 1399, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_spaces(double, start_mark))
  File "/usr/local/lib/python3.9/dist-packages/ruamel/yaml/scanner.py", line 1498, in scan_flow_scalar_spaces
    raise ScannerError(
ruamel.yaml.scanner.ScannerError: while scanning a quoted scalar
  in "/home/ubuntu/.config/aliyunpan.yaml", line 1, column 16
found unexpected end of stream
  in "/home/ubuntu/.config/aliyunpan.yaml", line 2, column 1

> 配置文件有问题

已解决。原来一直用-t  参数 ，没有在aliyunpan.yaml写入token，不知道为什么yaml文件写入了过期的token。 麻烦关闭issues

**Comment by wxy1343** [comment]
配置文件有问题
